### PR TITLE
make nicer jigs for aligning rails

### PR DESCRIPTION
**Pull request by astrobunny**
Make some STLs based on the Y-jig for all X, Y and Z rails, for the 180mm Micron.

image

Started because the original z-jig was difficult to use properly, had to have a straight block behind or the extrusion already there to use it. Instead I just modelled it on the Y-rail style, and added a cutout so it can still be dual-use like the current one, but touches more extrusion, so has less play and gives a more confident alignment.

This is the z-jig in action:

image

image

image

The original Y-rail jig was too long for the 180mm one, so if you put them both on the ends of the extrusion the area was too short and the rail could not be centered using the jigs.

The original X-rail jig only centered the rail vertically, and you had to manually center the x somehow.

image

This adds Y-rail  and X-rail jigs that give you both the correct centering for them vertically and horizontally.

### CODE REVIEW

**Comment by hartk1213** [comment]
these look great. do you happen to have the cad file for them as well? if you could add that to this that would be great

**Comment by davidsiaw** [comment]
@hartk1213 I made them in blender. sorry. The STL has as much info as the blender file does of the component.

**Comment by astrobunny** [comment]
@hartk1213 I made them in blender, sorry. The STL contains as much info as the blender file.

**Comment by hartk1213** [comment]
Ok no worries..I can convert them to CAD in fusion 👍🏼

**Pull request merged**
